import "./globals.css";

import { Navbar } from "@/components/Export";
import ReduxProvider from "@/redux/ReduxProvider";

import NextUI from "@/components/NextUI";

export const metadata = {
  title: "Atharv Vani",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
      <html lang="en" className="bg-theme-white">
        <body className="">
          <NextUI>
            <Navbar />
            {children}
          </NextUI>
        </body>
      </html>
    </ReduxProvider>
  );
}
